apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-picking
spec:
  template:
    spec:
      containers:
        - name: wave-picking
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"