apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-picking
spec:
  template:
    spec:
      containers:
      - name: wave-picking
        image: app-image
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        envFrom: 
          - configMapRef:
              name: wave-picking
          - secretRef:
              name: wave-picking
        livenessProbe:
          httpGet:
            path: /status/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3



